# Generated by Django 6.0.1 on 2026-01-26 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassificacaoReceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (valid_time - início)",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (valid_time - fim). Valor sentinela 9999-12-31 indica vigência ativa.",
                        verbose_name="Data de Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data/Hora de Registro Início",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 23:59:59 indica registro ativo.",
                        verbose_name="Data/Hora de Registro Fim",
                    ),
                ),
                (
                    "classificacao_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da classificação estatística (GSIM StatisticalClassification.identifier)",
                        max_length=100,
                        verbose_name="Identificador da Classificação",
                    ),
                ),
                (
                    "classificacao_nome",
                    models.CharField(
                        help_text="Nome oficial da classificação estatística (GSIM StatisticalClassification.name)",
                        max_length=255,
                        verbose_name="Nome da Classificação",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada da classificação, seu propósito e escopo",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "tipo_classificacao",
                    models.CharField(
                        choices=[("hierárquica", "Hierárquica"), ("linear", "Linear")],
                        default="hierárquica",
                        help_text="Tipo da classificação (hierárquica ou linear)",
                        max_length=20,
                        verbose_name="Tipo de Classificação",
                    ),
                ),
                (
                    "numero_niveis",
                    models.IntegerField(
                        help_text="Número de níveis hierárquicos da classificação. Para o Classificador de Receita MG, o valor é 9.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Número de Níveis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classificação de Receita",
                "verbose_name_plural": "Classificações de Receita",
                "db_table": "classificacao_receita",
            },
        ),
        migrations.CreateModel(
            name="NivelHierarquico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (valid_time - início)",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (valid_time - fim). Valor sentinela 9999-12-31 indica vigência ativa.",
                        verbose_name="Data de Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data/Hora de Registro Início",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 23:59:59 indica registro ativo.",
                        verbose_name="Data/Hora de Registro Fim",
                    ),
                ),
                (
                    "nivel_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único do nível hierárquico (GSIM ClassificationLevel.identifier)",
                        max_length=100,
                        verbose_name="Identificador do Nível",
                    ),
                ),
                (
                    "nivel_numero",
                    models.IntegerField(
                        help_text="Número sequencial do nível na hierarquia, começando em 1 para o nível mais agregado",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Número do Nível",
                    ),
                ),
                (
                    "nivel_nome",
                    models.CharField(
                        help_text='Nome do nível hierárquico (ex: "Categoria Econômica", "Origem", "Espécie")',
                        max_length=255,
                        verbose_name="Nome do Nível",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do nível, seu propósito e conteúdo",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "estrutura_codigo",
                    models.CharField(
                        blank=True,
                        help_text='Padrão de estrutura do código neste nível (ex: "C", "C.O", "C.O.E")',
                        max_length=50,
                        verbose_name="Estrutura do Código",
                    ),
                ),
                (
                    "tipo_codigo",
                    models.CharField(
                        choices=[
                            ("numérico", "Numérico"),
                            ("alfabético", "Alfabético"),
                            ("alfanumérico", "Alfanumérico"),
                        ],
                        default="numérico",
                        help_text="Tipo do código no nível (numérico, alfabético, alfanumérico)",
                        max_length=20,
                        verbose_name="Tipo de Código",
                    ),
                ),
                (
                    "classificacao",
                    models.ForeignKey(
                        help_text="Referência à classificação estatística à qual este nível pertence",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="niveis",
                        to="core.classificacaoreceita",
                        verbose_name="Classificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível Hierárquico",
                "verbose_name_plural": "Níveis Hierárquicos",
                "db_table": "nivel_hierarquico",
            },
        ),
        migrations.CreateModel(
            name="ItemClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (valid_time - início)",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (valid_time - fim). Valor sentinela 9999-12-31 indica vigência ativa.",
                        verbose_name="Data de Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data/Hora de Registro Início",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 23:59:59 indica registro ativo.",
                        verbose_name="Data/Hora de Registro Fim",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único do item de classificação",
                        max_length=100,
                        verbose_name="Identificador do Item",
                    ),
                ),
                (
                    "codigo_completo",
                    models.CharField(
                        db_index=True,
                        help_text='Código completo formatado (ex: "1.0.1.1.01.1.1.01.001")',
                        max_length=50,
                        verbose_name="Código Completo",
                    ),
                ),
                (
                    "codigo_numerico",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Código numérico de 13 dígitos sem formatação",
                        validators=[
                            django.core.validators.MinValueValidator(1000000000000),
                            django.core.validators.MaxValueValidator(9999999999999),
                        ],
                        verbose_name="Código Numérico",
                    ),
                ),
                (
                    "nome_oficial",
                    models.CharField(
                        help_text="Nome oficial do item de classificação",
                        max_length=500,
                        verbose_name="Nome Oficial",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do item de classificação",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "item_gerado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o item foi gerado automaticamente para completar o nível",
                        verbose_name="Item Gerado",
                    ),
                ),
                (
                    "valido_atualmente",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o item está atualmente válido na classificação",
                        verbose_name="Válido Atualmente",
                    ),
                ),
                (
                    "parent_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência ao item do nível imediatamente superior na hierarquia. NULL para itens do nível 1.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_itens",
                        to="core.itemclassificacao",
                        verbose_name="Item Pai",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        help_text="Referência ao nível hierárquico ao qual este item pertence",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens",
                        to="core.nivelhierarquico",
                        verbose_name="Nível Hierárquico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Classificação",
                "verbose_name_plural": "Itens de Classificação",
                "db_table": "item_classificacao",
            },
        ),
        migrations.CreateModel(
            name="SerieClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (valid_time - início)",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (valid_time - fim). Valor sentinela 9999-12-31 indica vigência ativa.",
                        verbose_name="Data de Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data/Hora de Registro Início",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 23:59:59 indica registro ativo.",
                        verbose_name="Data/Hora de Registro Fim",
                    ),
                ),
                (
                    "serie_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da série de classificações (GSIM ClassificationSeries.identifier)",
                        max_length=100,
                        verbose_name="Identificador da Série",
                    ),
                ),
                (
                    "serie_nome",
                    models.CharField(
                        help_text="Nome oficial da série de classificações (GSIM ClassificationSeries.name)",
                        max_length=255,
                        verbose_name="Nome da Série",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada da série de classificações e seu propósito",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "orgao_responsavel",
                    models.CharField(
                        blank=True,
                        help_text="Órgão ou entidade responsável pela manutenção da série de classificações",
                        max_length=255,
                        verbose_name="Órgão Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Série de Classificações",
                "verbose_name_plural": "Séries de Classificações",
                "db_table": "serie_classificacao",
                "indexes": [
                    models.Index(
                        fields=["serie_id", "data_registro_fim"], name="idx_serie_registro_fim"
                    ),
                    models.Index(
                        fields=["data_vigencia_inicio", "data_vigencia_fim"],
                        name="idx_serie_vigencia",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("serie_id", "data_registro_inicio"), name="unique_serie_registro"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="classificacaoreceita",
            name="serie",
            field=models.ForeignKey(
                help_text="Referência à série de classificações à qual esta classificação pertence",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classificacoes",
                to="core.serieclassificacao",
                verbose_name="Série de Classificações",
            ),
        ),
        migrations.CreateModel(
            name="VersaoClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (valid_time - início)",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (valid_time - fim). Valor sentinela 9999-12-31 indica vigência ativa.",
                        verbose_name="Data de Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data/Hora de Registro Início",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 23:59:59 indica registro ativo.",
                        verbose_name="Data/Hora de Registro Fim",
                    ),
                ),
                (
                    "versao_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da versão da classificação",
                        max_length=100,
                        verbose_name="Identificador da Versão",
                    ),
                ),
                (
                    "versao_numero",
                    models.CharField(
                        help_text='Número ou identificador da versão (ex: "2024", "v1.0")',
                        max_length=50,
                        verbose_name="Número da Versão",
                    ),
                ),
                (
                    "versao_nome",
                    models.CharField(
                        blank=True,
                        help_text="Nome descritivo da versão",
                        max_length=255,
                        verbose_name="Nome da Versão",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição das mudanças e características desta versão. Versões são reservadas para mudanças que alteram fronteiras conceituais entre categorias.",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "data_lancamento",
                    models.DateField(
                        blank=True,
                        help_text="Data oficial de lançamento/publicação da versão",
                        null=True,
                        verbose_name="Data de Lançamento",
                    ),
                ),
                (
                    "classificacao",
                    models.ForeignKey(
                        help_text="Referência à classificação estatística à qual esta versão pertence",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versoes",
                        to="core.classificacaoreceita",
                        verbose_name="Classificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão da Classificação",
                "verbose_name_plural": "Versões da Classificação",
                "db_table": "versao_classificacao",
            },
        ),
        migrations.CreateModel(
            name="VarianteClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (valid_time - início)",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (valid_time - fim). Valor sentinela 9999-12-31 indica vigência ativa.",
                        verbose_name="Data de Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data/Hora de Registro Início",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 23:59:59 indica registro ativo.",
                        verbose_name="Data/Hora de Registro Fim",
                    ),
                ),
                (
                    "variante_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da variante de classificação",
                        max_length=100,
                        verbose_name="Identificador da Variante",
                    ),
                ),
                (
                    "variante_nome",
                    models.CharField(
                        help_text="Nome descritivo da variante",
                        max_length=255,
                        verbose_name="Nome da Variante",
                    ),
                ),
                (
                    "tipo_variante",
                    models.CharField(
                        choices=[
                            ("extensão", "Extensão"),
                            ("agregação", "Agregação"),
                            ("reagrupamento", "Reagrupamento"),
                            ("outro", "Outro"),
                        ],
                        help_text="Tipo da variante (extensão, agregação, reagrupamento, outro)",
                        max_length=20,
                        verbose_name="Tipo de Variante",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada da variante, seu propósito e diferenças em relação à classificação de origem",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "proposito",
                    models.CharField(
                        blank=True,
                        help_text='Propósito específico da variante (ex: "relatório específico", "norma estadual")',
                        max_length=255,
                        verbose_name="Propósito",
                    ),
                ),
                (
                    "classificacao",
                    models.ForeignKey(
                        help_text="Referência à classificação estatística na qual esta variante se baseia",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variantes",
                        to="core.classificacaoreceita",
                        verbose_name="Classificação de Origem",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência à versão da classificação na qual esta variante se baseia",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variantes",
                        to="core.versaoclassificacao",
                        verbose_name="Versão de Origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de Classificação",
                "verbose_name_plural": "Variantes de Classificação",
                "db_table": "variante_classificacao",
            },
        ),
        migrations.AddIndex(
            model_name="nivelhierarquico",
            index=models.Index(
                fields=["nivel_id", "data_registro_fim"], name="idx_nivel_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="nivelhierarquico",
            index=models.Index(
                fields=["classificacao", "nivel_numero"], name="idx_nivel_classificacao_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="nivelhierarquico",
            constraint=models.UniqueConstraint(
                fields=("nivel_id", "data_registro_inicio"), name="unique_nivel_registro"
            ),
        ),
        migrations.AddConstraint(
            model_name="nivelhierarquico",
            constraint=models.UniqueConstraint(
                fields=("classificacao", "nivel_numero", "data_registro_inicio"),
                name="unq_nivel_numero_classif",
            ),
        ),
        migrations.AddIndex(
            model_name="itemclassificacao",
            index=models.Index(
                fields=["item_id", "data_registro_fim"], name="idx_item_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="itemclassificacao",
            index=models.Index(
                fields=["codigo_numerico", "data_registro_fim"], name="idx_item_codigo_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="itemclassificacao",
            index=models.Index(
                fields=["nivel", "data_vigencia_inicio"], name="idx_item_nivel_vigencia"
            ),
        ),
        migrations.AddIndex(
            model_name="itemclassificacao",
            index=models.Index(fields=["parent_item"], name="idx_item_parent"),
        ),
        migrations.AddConstraint(
            model_name="itemclassificacao",
            constraint=models.UniqueConstraint(
                fields=("item_id", "data_registro_inicio"), name="unique_item_registro"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemclassificacao",
            constraint=models.UniqueConstraint(
                fields=("codigo_numerico", "data_registro_inicio"),
                name="unique_codigo_numerico_registro",
            ),
        ),
        migrations.AddIndex(
            model_name="classificacaoreceita",
            index=models.Index(
                fields=["classificacao_id", "data_registro_fim"],
                name="idx_classificacao_registro_fim",
            ),
        ),
        migrations.AddIndex(
            model_name="classificacaoreceita",
            index=models.Index(
                fields=["serie", "data_vigencia_inicio"], name="idx_classif_serie_vig"
            ),
        ),
        migrations.AddConstraint(
            model_name="classificacaoreceita",
            constraint=models.UniqueConstraint(
                fields=("classificacao_id", "data_registro_inicio"),
                name="unique_classificacao_registro",
            ),
        ),
        migrations.AddIndex(
            model_name="versaoclassificacao",
            index=models.Index(
                fields=["versao_id", "data_registro_fim"], name="idx_versao_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="versaoclassificacao",
            index=models.Index(
                fields=["classificacao", "data_vigencia_inicio"],
                name="idx_versao_classif_vig",
            ),
        ),
        migrations.AddConstraint(
            model_name="versaoclassificacao",
            constraint=models.UniqueConstraint(
                fields=("versao_id", "data_registro_inicio"), name="unique_versao_registro"
            ),
        ),
        migrations.AddIndex(
            model_name="varianteclassificacao",
            index=models.Index(
                fields=["variante_id", "data_registro_fim"], name="idx_variante_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="varianteclassificacao",
            index=models.Index(
                fields=["classificacao", "data_vigencia_inicio"],
                name="idx_variante_classif_vig",
            ),
        ),
        migrations.AddConstraint(
            model_name="varianteclassificacao",
            constraint=models.UniqueConstraint(
                fields=("variante_id", "data_registro_inicio"), name="unique_variante_registro"
            ),
        ),
    ]
