# Generated by Django 6.0.1 on 2026-03-31 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseLegalTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "base_legal_tecnica_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da entidade norma/ato (chave semântica). Sugestão: [{tipo_legal}-{numero}-{orgao_responsavel}], ex.: CR-88-PLANALTO, LC-101-BRA.",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use apenas letras maiúsculas e números, separados por traço (-). Não utilize caracteres especiais. Ex.: CR-88-PLANALTO.",
                                regex="^[A-Z0-9]+(-[A-Z0-9]+)*$",
                            )
                        ],
                        verbose_name="Identificador da Base Legal/Técnica",
                    ),
                ),
                (
                    "base_legal_tecnica_ref",
                    models.IntegerField(
                        help_text="Identificador numérico estável da norma/ato/manuais, usado na chave primária lógica. Mesmo valor para todas as linhas que pertencem à mesma entidade (mesmo base_legal_tecnica_id).",
                        verbose_name="Referência Numérica da Base Legal/Técnica",
                    ),
                ),
                (
                    "esfera_federativa",
                    models.CharField(
                        choices=[
                            ("BRA", "BRA"),
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AM", "AM"),
                            ("AP", "AP"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MG", "MG"),
                            ("MS", "MS"),
                            ("MT", "MT"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("PR", "PR"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("RS", "RS"),
                            ("SC", "SC"),
                            ("SE", "SE"),
                            ("SP", "SP"),
                            ("TO", "TO"),
                        ],
                        help_text="Esfera federativa à qual a norma se aplica (BRA ou sigla de UF).",
                        max_length=3,
                        verbose_name="Esfera Federativa",
                    ),
                ),
                (
                    "tipo_legal",
                    models.CharField(
                        choices=[
                            ("adct", "adct"),
                            ("cr", "cr"),
                            ("ce", "ce"),
                            ("dec", "dec"),
                            ("dec-lei", "dec-lei"),
                            ("ec", "ec"),
                            ("inst-norm", "inst-norm"),
                            ("jrsp", "jrsp"),
                            ("lc", "lc"),
                            ("lce", "lce"),
                            ("ldo", "ldo"),
                            ("lo", "lo"),
                            ("loa", "loa"),
                            ("lom", "lom"),
                            ("loe", "loe"),
                            ("man", "man"),
                            ("ntj", "ntj"),
                            ("ntt", "ntt"),
                            ("parecer", "parecer"),
                            ("pec", "pec"),
                            ("pl", "pl"),
                            ("port", "port"),
                            ("port-conj", "port-conj"),
                            ("ppa", "ppa"),
                            ("ppag", "ppag"),
                            ("reg", "reg"),
                            ("sum", "sum"),
                            ("sum-vinc", "sum-vinc"),
                        ],
                        help_text="Tipo da norma jurídica/técnica (ex.: cr, lc, man, ntj, ntt, port).",
                        max_length=20,
                        verbose_name="Tipo da Norma (sigla)",
                    ),
                ),
                (
                    "numero_codigo",
                    models.CharField(
                        help_text="Número ou código identificador da norma (ex.: número da lei, decreto, portaria).",
                        max_length=50,
                        verbose_name="Número/Código da Norma",
                    ),
                ),
                (
                    "data_edicao",
                    models.DateField(
                        help_text="Data em que a autoridade competente editou/assinou o ato normativo/instrumento técnico.",
                        verbose_name="Data de Edição/Assinatura",
                    ),
                ),
                (
                    "orgao_responsavel",
                    models.CharField(
                        choices=[
                            ("Camara-BRA", "Câmara dos Deputados"),
                            ("Congresso-BRA", "Congresso Nacional"),
                            ("Planalto-BRA", "Presidência da República / Planalto"),
                            ("Senado-BRA", "Senado Federal"),
                            ("AGU-BRA", "Advocacia-Geral da União"),
                            ("CGU-BRA", "Controladoria-Geral da União"),
                            ("STF-BRA", "Supremo Tribunal Federal"),
                            ("STJ-BRA", "Superior Tribunal de Justiça"),
                            ("TCU-BRA", "Tribunal de Contas da União"),
                            ("TRF-BRA", "Tribunal Regional Federal"),
                            ("BACEN-BRA", "Banco Central do Brasil"),
                            ("RFB-BRA", "Receita Federal do Brasil"),
                            ("SOF-BRA", "Secretaria de Orçamento Federal"),
                            ("STN-BRA", "Secretaria do Tesouro Nacional"),
                            ("AGE-MG", "Advocacia-Geral do Estado de Minas Gerais"),
                            ("AL-MG", "Assembleia Legislativa de Minas Gerais"),
                            ("CGE-MG", "Controladoria-Geral do Estado de Minas Gerais"),
                            ("SEF-MG", "Secretaria de Estado da Fazenda de Minas Gerais"),
                            (
                                "SEPLAG-MG",
                                "Secretaria de Estado de Planejamento e Gestão de Minas Gerais",
                            ),
                            ("TCE-MG", "Tribunal de Contas do Estado de Minas Gerais"),
                            ("TJ-MG", "Tribunal de Justiça de Minas Gerais"),
                        ],
                        help_text="Órgão ou entidade responsável pela promulgação do ato normativo ou instrumento jurídico/técnico. Valores válidos: dominios/orgaos_entidades.yaml (domainRef).",
                        max_length=255,
                        verbose_name="Órgão/Entidade Responsável",
                    ),
                ),
                (
                    "titulo_norma",
                    models.CharField(
                        blank=True,
                        help_text="Título oficial ou nome curto da norma.",
                        max_length=255,
                        verbose_name="Título da Norma",
                    ),
                ),
                (
                    "ementa",
                    models.TextField(
                        blank=True, help_text="Ementa ou resumo da norma.", verbose_name="Ementa"
                    ),
                ),
                (
                    "url_fonte",
                    models.CharField(
                        blank=True,
                        help_text="URL estável para consulta ao texto da norma (Planalto, DO, portal da casa legislativa).",
                        max_length=500,
                        verbose_name="URL da Fonte",
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data a partir da qual a norma passa a ter vigência.",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data até a qual a norma permanece vigente (9999-12-31 indica vigência ativa).",
                        verbose_name="Data do Fim da Vigência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Legal/Técnica",
                "verbose_name_plural": "Bases Legais/Técnicas",
                "db_table": "base_legal_tecnica",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("base_legal_tecnica_ref", "data_vigencia_inicio"),
                        name="unique_base_legal_tecnica_ref_vigencia",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (dd/mm/aaaa).",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (dd/mm/aaaa). Valor sentinela 31/12/9999 (ou 9999-12-31) indica vigência ativa no momento corrente e futuro.",
                        verbose_name="Data do Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data de Início do Registro",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 00:00:00 indica registro ativo no momento corrente e futuro.",
                        verbose_name="Data do Fim do Registro",
                    ),
                ),
                (
                    "classificacao_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da classificação estatística (chave semântica) (classificacao_id).",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use apenas letras maiúsculas e números, separados por traço (-). Não utilize caracteres especiais. Ex.: CR-88-PLANALTO.",
                                regex="^[A-Z0-9]+(-[A-Z0-9]+)*$",
                            )
                        ],
                        verbose_name="Identificador da Classificação",
                    ),
                ),
                (
                    "classificacao_ref",
                    models.IntegerField(
                        help_text="Identificador numérico estável da classificação estatística, usado na chave primária. Mesmo valor para todas as linhas que pertencem à mesma entidade (mesmo classificacao_id), (classificacao_ref).",
                        verbose_name="Referência Numérica da Classificação",
                    ),
                ),
                (
                    "classificacao_nome",
                    models.CharField(
                        help_text="Nome oficial da classificação estatística (classificacao_nome).",
                        max_length=255,
                        verbose_name="Nome da Classificação",
                    ),
                ),
                (
                    "classificacao_descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada da classificação, seu propósito e escopo (descricao).",
                        verbose_name="Descrição da Classificação",
                    ),
                ),
                (
                    "tipo_classificacao",
                    models.CharField(
                        choices=[("hierárquica", "Hierárquica"), ("linear", "Linear")],
                        default="hierárquica",
                        help_text="Tipo da classificação (hierárquica ou linear)",
                        max_length=20,
                        verbose_name="Tipo de Classificação",
                    ),
                ),
                (
                    "numero_niveis",
                    models.IntegerField(
                        help_text="Número de níveis hierárquicos da classificação. Para o Classificador de Receita MG, o valor é 9 (numero_niveis).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Número de Níveis",
                    ),
                ),
                (
                    "numero_digitos",
                    models.IntegerField(
                        blank=True,
                        help_text="Quantidade total de dígitos do código na classificação (ex.: 8 para a base União, 10 ou 13 para MG conforme a edição).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Número de Dígitos do Código",
                    ),
                ),
                (
                    "base_legal_tecnica_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="base_legal_tecnica_id",
                        help_text="Identificador da norma ou ato que institui ou altera esta classificação, quando aplicável. Referência à tabela base_legal_tecnica. Opcional; pode ficar em branco quando a classificação decorre de múltiplas normas ou de convenção interna.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classificacoes_relacionadas",
                        to="core.baselegaltecnica",
                        verbose_name="Base Legal/Técnica de Referência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classificação de Receita",
                "verbose_name_plural": "Classificações de Receita",
                "db_table": "classificacao",
            },
        ),
        migrations.CreateModel(
            name="NivelHierarquico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (dd/mm/aaaa).",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (dd/mm/aaaa). Valor sentinela 31/12/9999 (ou 9999-12-31) indica vigência ativa no momento corrente e futuro.",
                        verbose_name="Data do Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data de Início do Registro",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 00:00:00 indica registro ativo no momento corrente e futuro.",
                        verbose_name="Data do Fim do Registro",
                    ),
                ),
                (
                    "nivel_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único do nível hierárquico (chave semântica).",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use apenas letras maiúsculas e números, separados por traço (-). Não utilize caracteres especiais. Ex.: CR-88-PLANALTO.",
                                regex="^[A-Z0-9]+(-[A-Z0-9]+)*$",
                            )
                        ],
                        verbose_name="Identificador do Nível",
                    ),
                ),
                (
                    "nivel_ref",
                    models.IntegerField(
                        blank=True,
                        help_text="Identificador numérico estável do nível hierárquico, usado na chave primária lógica (bitemporal). Mesmo valor para todas as linhas que pertencem ao mesmo nível conceitual (mesmo nivel_id).",
                        null=True,
                        verbose_name="Referência Numérica do Nível",
                    ),
                ),
                (
                    "nivel_numero",
                    models.IntegerField(
                        help_text="Número sequencial do nível na hierarquia, começando em 1 para o nível mais agregado",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Número do Nível",
                    ),
                ),
                (
                    "nivel_nome",
                    models.CharField(
                        help_text='Nome do nível hierárquico (ex: "Categoria Econômica", "Origem", "Espécie")',
                        max_length=255,
                        verbose_name="Nome do Nível",
                    ),
                ),
                (
                    "nivel_descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do nível, seu propósito e conteúdo",
                        verbose_name="Descrição do Nível",
                    ),
                ),
                (
                    "estrutura_codigo",
                    models.CharField(
                        blank=True,
                        help_text='Padrão de estrutura do código neste nível (ex.: "X.0.0.0.00.0.00.000", para quando apenas o primeiro nível estiver detalhado)',
                        max_length=50,
                        verbose_name="Estrutura do Código",
                    ),
                ),
                (
                    "numero_digitos",
                    models.IntegerField(
                        blank=True,
                        help_text="Quantidade de dígitos do código neste nível.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Número de Dígitos",
                    ),
                ),
                (
                    "tipo_codigo",
                    models.CharField(
                        choices=[
                            ("numérico", "Numérico"),
                            ("alfabético", "Alfabético"),
                            ("alfanumérico", "Alfanumérico"),
                        ],
                        default="numérico",
                        help_text="Tipo do código no nível (numérico, alfabético, alfanumérico)",
                        max_length=20,
                        verbose_name="Tipo de Código",
                    ),
                ),
                (
                    "classificacao_id",
                    models.ForeignKey(
                        db_column="classificacao_id",
                        help_text="Referência à classificação estatística à qual este nível pertence",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="niveis",
                        to="core.classificacao",
                        verbose_name="Classificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível Hierárquico",
                "verbose_name_plural": "Níveis Hierárquicos",
                "db_table": "nivel_hierarquico",
            },
        ),
        migrations.CreateModel(
            name="ItemClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (dd/mm/aaaa).",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (dd/mm/aaaa). Valor sentinela 31/12/9999 (ou 9999-12-31) indica vigência ativa no momento corrente e futuro.",
                        verbose_name="Data do Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data de Início do Registro",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 00:00:00 indica registro ativo no momento corrente e futuro.",
                        verbose_name="Data do Fim do Registro",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        db_index=True,
                        help_text="Chave semântica do item: prefixo IT- seguido do código canônico (receita_cod), ex.: IT-1000000000000. Deve coincidir com receita_cod.",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="item_id deve ser IT- seguido do código canônico da receita (8 a 13 dígitos), ex.: IT-1000000000000.",
                                regex="^IT-[0-9]{8,13}$",
                            )
                        ],
                        verbose_name="Identificador do Item",
                    ),
                ),
                (
                    "item_ref",
                    models.IntegerField(
                        blank=True,
                        help_text="Identificador numérico estável do item, usado na chave primária lógica (bitemporal). Mesmo valor para todas as linhas que pertencem à mesma entidade (mesmo item_id).",
                        null=True,
                        verbose_name="Referência Numérica do Item",
                    ),
                ),
                (
                    "receita_cod",
                    models.CharField(
                        db_index=True,
                        help_text="Código numérico canônico da natureza de receita orçamentária",
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="receita_cod must be 8-13 digits", regex="^[0-9]{8,13}$"
                            )
                        ],
                        verbose_name="Código Canônico da Natureza de Receita",
                    ),
                ),
                (
                    "matriz",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o item é natureza agregadora (Matriz) ou item folha (Detalhe). Quando marcado (TRUE), indica item agregador; quando desmarcado (FALSE), item detalhe em que a execução orçamentária pode ser registrada.",
                        verbose_name="Identificador de Matriz",
                    ),
                ),
                (
                    "receita_nome",
                    models.CharField(
                        blank=True,
                        help_text="Nome da natureza de receita orçamentária, baseado no fato gerador para rotular a origem e o tipo do recurso que ingressa nos cofres públicos.",
                        max_length=500,
                        null=True,
                        verbose_name="Nome da Classificação por Natureza de Receita",
                    ),
                ),
                (
                    "receita_descricao",
                    models.TextField(
                        blank=True,
                        help_text="Texto descritivo que complementa o nome, esclarecendo significado, escopo e finalidade da natureza de receita, incluindo detalhes de conceito, abrangência e casos limítrofes.",
                        null=True,
                        verbose_name="Descrição da Natureza de Receita",
                    ),
                ),
                (
                    "base_legal_tecnica_referencia",
                    models.CharField(
                        blank=True,
                        help_text='Trecho específico da base legal/técnica (ex.: artigo, parágrafo, inciso, anexo, item), quando a fundamentação não é a norma como um todo. Ex.: "Art. 8º, § 1º".',
                        max_length=255,
                        null=True,
                        verbose_name="Referência ao Excerto da Base Legal/Técnica",
                    ),
                ),
                (
                    "destinacao_legal",
                    models.CharField(
                        blank=True,
                        help_text="Indicação da destinação ou vinculação legal aplicável à receita classificada neste item, quando a norma estabelece regras de aplicação (ex.: percentual para educação, saúde, fundos).",
                        max_length=500,
                        null=True,
                        verbose_name="Destinação Legal",
                    ),
                ),
                (
                    "informacoes_gerenciais",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes técnicos e operacionais sobre o contexto de criação/aplicação da natureza de receita: critérios de uso, integrações (ex.: SISOR), notas de implementação, decisões de governança.",
                        null=True,
                        verbose_name="Informações Gerenciais",
                    ),
                ),
                (
                    "item_gerado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o item existe por regra (gerado automaticamente a partir de uma agregadora) ou se consta explicitamente no ementário oficial.",
                        verbose_name="Item Gerado Automaticamente",
                    ),
                ),
                (
                    "base_legal_tecnica_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="base_legal_tecnica_id",
                        help_text="Identificador da norma ou ato que institui ou altera esta natureza de receita, quando aplicável. Referência à tabela base_legal_tecnica. Opcional; pode ficar em branco quando a natureza de receita decorre de múltiplas normas ou de convenção interna.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_classificacao_relacionados",
                        to="core.baselegaltecnica",
                        verbose_name="Base Legal/Técnica de Referência",
                    ),
                ),
                (
                    "classificacao_id",
                    models.ForeignKey(
                        db_column="classificacao_id",
                        help_text="Referência à classificação estatística à qual este item pertence",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens",
                        to="core.classificacao",
                        verbose_name="Classificação",
                    ),
                ),
                (
                    "parent_item_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_item_id",
                        help_text="Referência ao item do nível imediatamente superior na hierarquia. NULL para itens do nível 1.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_itens",
                        to="core.itemclassificacao",
                        verbose_name="Item Pai",
                    ),
                ),
                (
                    "nivel_id",
                    models.ForeignKey(
                        db_column="nivel_id",
                        help_text="Referência ao nível hierárquico ao qual este item pertence",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens",
                        to="core.nivelhierarquico",
                        verbose_name="Nível Hierárquico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Classificação",
                "verbose_name_plural": "Itens de Classificação",
                "db_table": "item_classificacao",
            },
        ),
        migrations.CreateModel(
            name="SerieClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (dd/mm/aaaa).",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (dd/mm/aaaa). Valor sentinela 31/12/9999 (ou 9999-12-31) indica vigência ativa no momento corrente e futuro.",
                        verbose_name="Data do Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data de Início do Registro",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 00:00:00 indica registro ativo no momento corrente e futuro.",
                        verbose_name="Data do Fim do Registro",
                    ),
                ),
                (
                    "serie_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da série de classificações (serie_id).",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use apenas letras maiúsculas e números, separados por traço (-). Não utilize caracteres especiais. Ex.: CR-88-PLANALTO.",
                                regex="^[A-Z0-9]+(-[A-Z0-9]+)*$",
                            )
                        ],
                        verbose_name="Identificador da Série",
                    ),
                ),
                (
                    "serie_ref",
                    models.IntegerField(
                        help_text="Identificador numérico estável da série de classificações, usado na chave primária. Mesmo valor para todas as linhas que pertencem à mesma entidade (mesmo serie_id), (serie_ref).",
                        verbose_name="Referência Numérica da Série",
                    ),
                ),
                (
                    "serie_nome",
                    models.CharField(
                        help_text="Nome oficial da série de classificações (serie_nome).",
                        max_length=255,
                        verbose_name="Nome da Série",
                    ),
                ),
                (
                    "serie_descricao",
                    models.TextField(
                        help_text="Descrição detalhada da série de classificações e seu propósito (serie_descricao).",
                        verbose_name="Descrição da Série",
                    ),
                ),
                (
                    "orgao_responsavel",
                    models.CharField(
                        choices=[
                            ("Camara-BRA", "Câmara dos Deputados"),
                            ("Congresso-BRA", "Congresso Nacional"),
                            ("Planalto-BRA", "Presidência da República / Planalto"),
                            ("Senado-BRA", "Senado Federal"),
                            ("AGU-BRA", "Advocacia-Geral da União"),
                            ("CGU-BRA", "Controladoria-Geral da União"),
                            ("STF-BRA", "Supremo Tribunal Federal"),
                            ("STJ-BRA", "Superior Tribunal de Justiça"),
                            ("TCU-BRA", "Tribunal de Contas da União"),
                            ("TRF-BRA", "Tribunal Regional Federal"),
                            ("BACEN-BRA", "Banco Central do Brasil"),
                            ("RFB-BRA", "Receita Federal do Brasil"),
                            ("SOF-BRA", "Secretaria de Orçamento Federal"),
                            ("STN-BRA", "Secretaria do Tesouro Nacional"),
                            ("AGE-MG", "Advocacia-Geral do Estado de Minas Gerais"),
                            ("AL-MG", "Assembleia Legislativa de Minas Gerais"),
                            ("CGE-MG", "Controladoria-Geral do Estado de Minas Gerais"),
                            ("SEF-MG", "Secretaria de Estado da Fazenda de Minas Gerais"),
                            (
                                "SEPLAG-MG",
                                "Secretaria de Estado de Planejamento e Gestão de Minas Gerais",
                            ),
                            ("TCE-MG", "Tribunal de Contas do Estado de Minas Gerais"),
                            ("TJ-MG", "Tribunal de Justiça de Minas Gerais"),
                        ],
                        help_text="Órgão ou entidade responsável pela manutenção da série de classificações. Valores válidos: dominios/orgaos_entidades.yaml (domainRef).",
                        max_length=255,
                        verbose_name="Órgão Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Série de Classificação",
                "verbose_name_plural": "Séries de Classificações",
                "db_table": "serie_classificacao",
                "indexes": [
                    models.Index(
                        fields=["serie_id", "data_registro_fim"], name="idx_serie_registro_fim"
                    ),
                    models.Index(
                        fields=["data_vigencia_inicio", "data_vigencia_fim"],
                        name="idx_serie_vigencia",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("serie_id", "data_vigencia_inicio", "data_registro_inicio"),
                        name="unique_serie_registro",
                    ),
                    models.UniqueConstraint(
                        fields=("serie_ref", "data_vigencia_inicio", "data_registro_inicio"),
                        name="unique_serie_ref_registro",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="classificacao",
            name="serie_id",
            field=models.ForeignKey(
                db_column="serie_id",
                help_text="Referência à série de classificações à qual esta classificação pertence (serie_id).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classificacoes",
                to="core.serieclassificacao",
                verbose_name="Série de Classificações",
            ),
        ),
        migrations.CreateModel(
            name="VersaoClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (dd/mm/aaaa).",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (dd/mm/aaaa). Valor sentinela 31/12/9999 (ou 9999-12-31) indica vigência ativa no momento corrente e futuro.",
                        verbose_name="Data do Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data de Início do Registro",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 00:00:00 indica registro ativo no momento corrente e futuro.",
                        verbose_name="Data do Fim do Registro",
                    ),
                ),
                (
                    "versao_ref",
                    models.IntegerField(
                        help_text="Identificador numérico estável da versão, usado na chave primária lógica (bitemporal). Mesmo valor para todas as linhas que pertencem à mesma entidade (mesmo versao_id).",
                        verbose_name="Referência Numérica da Versão",
                    ),
                ),
                (
                    "versao_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da versão da classificação",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use apenas letras maiúsculas e números, separados por traço (-). Não utilize caracteres especiais. Ex.: CR-88-PLANALTO.",
                                regex="^[A-Z0-9]+(-[A-Z0-9]+)*$",
                            )
                        ],
                        verbose_name="Identificador da Versão",
                    ),
                ),
                (
                    "versao_numero",
                    models.CharField(
                        help_text='Número ou identificador da versão (ex: "2024", "v1.0")',
                        max_length=50,
                        verbose_name="Número da Versão",
                    ),
                ),
                (
                    "versao_nome",
                    models.CharField(
                        blank=True,
                        help_text="Nome descritivo da versão",
                        max_length=255,
                        verbose_name="Nome da Versão",
                    ),
                ),
                (
                    "versao_descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição das mudanças e características desta versão. Versões são reservadas para mudanças que alteram fronteiras conceituais entre categorias.",
                        verbose_name="Descrição da Versão",
                    ),
                ),
                (
                    "data_lancamento",
                    models.DateField(
                        blank=True,
                        help_text="Data oficial de lançamento/publicação da versão",
                        null=True,
                        verbose_name="Data de Lançamento",
                    ),
                ),
                (
                    "classificacao",
                    models.ForeignKey(
                        help_text="Referência à classificação estatística à qual esta versão pertence",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versoes",
                        to="core.classificacao",
                        verbose_name="Classificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão da Classificação",
                "verbose_name_plural": "Versões da Classificação",
                "db_table": "versao_classificacao",
            },
        ),
        migrations.CreateModel(
            name="VarianteClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_vigencia_inicio",
                    models.DateField(
                        help_text="Data de início da vigência no domínio orçamentário (dd/mm/aaaa).",
                        verbose_name="Data de Início da Vigência",
                    ),
                ),
                (
                    "data_vigencia_fim",
                    models.DateField(
                        help_text="Data de fim da vigência (dd/mm/aaaa). Valor sentinela 31/12/9999 (ou 9999-12-31) indica vigência ativa no momento corrente e futuro.",
                        verbose_name="Data do Fim da Vigência",
                    ),
                ),
                (
                    "data_registro_inicio",
                    models.DateTimeField(
                        help_text="Data e hora em que o sistema registrou esta informação (transaction_time - início)",
                        verbose_name="Data de Início do Registro",
                    ),
                ),
                (
                    "data_registro_fim",
                    models.DateTimeField(
                        help_text="Data e hora em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 00:00:00 indica registro ativo no momento corrente e futuro.",
                        verbose_name="Data do Fim do Registro",
                    ),
                ),
                (
                    "variante_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador único da variante de classificação",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use apenas letras maiúsculas e números, separados por traço (-). Não utilize caracteres especiais. Ex.: CR-88-PLANALTO.",
                                regex="^[A-Z0-9]+(-[A-Z0-9]+)*$",
                            )
                        ],
                        verbose_name="Identificador da Variante",
                    ),
                ),
                (
                    "variante_nome",
                    models.CharField(
                        help_text="Nome descritivo da variante",
                        max_length=255,
                        verbose_name="Nome da Variante",
                    ),
                ),
                (
                    "tipo_variante",
                    models.CharField(
                        choices=[
                            ("extensão", "Extensão"),
                            ("agregação", "Agregação"),
                            ("reagrupamento", "Reagrupamento"),
                            ("outro", "Outro"),
                        ],
                        help_text="Tipo da variante (extensão, agregação, reagrupamento, outro)",
                        max_length=20,
                        verbose_name="Tipo de Variante",
                    ),
                ),
                (
                    "variante_descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada da variante, seu propósito e diferenças em relação à classificação de origem",
                        verbose_name="Descrição da Variante",
                    ),
                ),
                (
                    "proposito",
                    models.CharField(
                        blank=True,
                        help_text='Propósito específico da variante (ex: "relatório específico", "norma estadual")',
                        max_length=255,
                        verbose_name="Propósito",
                    ),
                ),
                (
                    "classificacao",
                    models.ForeignKey(
                        help_text="Referência à classificação estatística na qual esta variante se baseia",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variantes",
                        to="core.classificacao",
                        verbose_name="Classificação de Origem",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referência à versão da classificação na qual esta variante se baseia",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variantes",
                        to="core.versaoclassificacao",
                        verbose_name="Versão de Origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de Classificação",
                "verbose_name_plural": "Variantes de Classificação",
                "db_table": "variante_classificacao",
            },
        ),
        migrations.AddIndex(
            model_name="nivelhierarquico",
            index=models.Index(
                fields=["nivel_id", "data_registro_fim"], name="idx_nivel_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="nivelhierarquico",
            index=models.Index(
                fields=["classificacao_id", "nivel_numero"], name="idx_nivel_classificacao_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="nivelhierarquico",
            constraint=models.UniqueConstraint(
                fields=("nivel_id", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_nivel_registro",
            ),
        ),
        migrations.AddConstraint(
            model_name="nivelhierarquico",
            constraint=models.UniqueConstraint(
                fields=(
                    "classificacao_id",
                    "nivel_numero",
                    "data_vigencia_inicio",
                    "data_registro_inicio",
                ),
                name="unq_nivel_numero_classif",
            ),
        ),
        migrations.AddConstraint(
            model_name="nivelhierarquico",
            constraint=models.UniqueConstraint(
                fields=("nivel_ref", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_nivel_ref_registro",
            ),
        ),
        migrations.AddIndex(
            model_name="itemclassificacao",
            index=models.Index(
                fields=["item_id", "data_registro_fim"], name="idx_item_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="itemclassificacao",
            index=models.Index(
                fields=["receita_cod", "data_registro_fim"], name="idx_item_codigo_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="itemclassificacao",
            index=models.Index(
                fields=["nivel_id", "data_vigencia_inicio"], name="idx_item_nivel_vigencia"
            ),
        ),
        migrations.AddIndex(
            model_name="itemclassificacao",
            index=models.Index(fields=["parent_item_id"], name="idx_item_parent"),
        ),
        migrations.AddConstraint(
            model_name="itemclassificacao",
            constraint=models.UniqueConstraint(
                fields=("item_id", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_item_registro",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemclassificacao",
            constraint=models.UniqueConstraint(
                fields=("item_ref", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_item_ref_registro",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemclassificacao",
            constraint=models.UniqueConstraint(
                fields=("receita_cod", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_receita_cod_registro",
            ),
        ),
        migrations.AddIndex(
            model_name="classificacao",
            index=models.Index(
                fields=["classificacao_id", "data_registro_fim"],
                name="idx_classificacao_registro_fim",
            ),
        ),
        migrations.AddIndex(
            model_name="classificacao",
            index=models.Index(
                fields=["serie_id", "data_vigencia_inicio"], name="idx_classif_serie_vig"
            ),
        ),
        migrations.AddConstraint(
            model_name="classificacao",
            constraint=models.UniqueConstraint(
                fields=("classificacao_id", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_classificacao_registro",
            ),
        ),
        migrations.AddConstraint(
            model_name="classificacao",
            constraint=models.UniqueConstraint(
                fields=("classificacao_ref", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_classificacao_ref_registro",
            ),
        ),
        migrations.AddIndex(
            model_name="versaoclassificacao",
            index=models.Index(
                fields=["versao_id", "data_registro_fim"], name="idx_versao_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="versaoclassificacao",
            index=models.Index(
                fields=["classificacao", "data_vigencia_inicio"], name="idx_versao_classif_vig"
            ),
        ),
        migrations.AddConstraint(
            model_name="versaoclassificacao",
            constraint=models.UniqueConstraint(
                fields=("versao_id", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_versao_registro",
            ),
        ),
        migrations.AddConstraint(
            model_name="versaoclassificacao",
            constraint=models.UniqueConstraint(
                fields=("versao_ref", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_versao_ref_registro",
            ),
        ),
        migrations.AddIndex(
            model_name="varianteclassificacao",
            index=models.Index(
                fields=["variante_id", "data_registro_fim"], name="idx_variante_registro_fim"
            ),
        ),
        migrations.AddIndex(
            model_name="varianteclassificacao",
            index=models.Index(
                fields=["classificacao", "data_vigencia_inicio"], name="idx_variante_classif_vig"
            ),
        ),
        migrations.AddConstraint(
            model_name="varianteclassificacao",
            constraint=models.UniqueConstraint(
                fields=("variante_id", "data_vigencia_inicio", "data_registro_inicio"),
                name="unique_variante_registro",
            ),
        ),
    ]
