# Generated by Django 6.0.1 on 2026-01-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificacaoreceita",
            name="data_registro_fim",
            field=models.DateField(
                help_text="Data em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 indica registro ativo.",
                verbose_name="Data de Registro Fim",
            ),
        ),
        migrations.AlterField(
            model_name="classificacaoreceita",
            name="data_registro_inicio",
            field=models.DateField(
                help_text="Data em que o sistema registrou esta informação (transaction_time - início)",
                verbose_name="Data de Registro Início",
            ),
        ),
        migrations.AlterField(
            model_name="itemclassificacao",
            name="data_registro_fim",
            field=models.DateField(
                help_text="Data em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 indica registro ativo.",
                verbose_name="Data de Registro Fim",
            ),
        ),
        migrations.AlterField(
            model_name="itemclassificacao",
            name="data_registro_inicio",
            field=models.DateField(
                help_text="Data em que o sistema registrou esta informação (transaction_time - início)",
                verbose_name="Data de Registro Início",
            ),
        ),
        migrations.AlterField(
            model_name="nivelhierarquico",
            name="data_registro_fim",
            field=models.DateField(
                help_text="Data em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 indica registro ativo.",
                verbose_name="Data de Registro Fim",
            ),
        ),
        migrations.AlterField(
            model_name="nivelhierarquico",
            name="data_registro_inicio",
            field=models.DateField(
                help_text="Data em que o sistema registrou esta informação (transaction_time - início)",
                verbose_name="Data de Registro Início",
            ),
        ),
        migrations.AlterField(
            model_name="serieclassificacao",
            name="data_registro_fim",
            field=models.DateField(
                help_text="Data em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 indica registro ativo.",
                verbose_name="Data de Registro Fim",
            ),
        ),
        migrations.AlterField(
            model_name="serieclassificacao",
            name="data_registro_inicio",
            field=models.DateField(
                help_text="Data em que o sistema registrou esta informação (transaction_time - início)",
                verbose_name="Data de Registro Início",
            ),
        ),
        migrations.AlterField(
            model_name="varianteclassificacao",
            name="data_registro_fim",
            field=models.DateField(
                help_text="Data em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 indica registro ativo.",
                verbose_name="Data de Registro Fim",
            ),
        ),
        migrations.AlterField(
            model_name="varianteclassificacao",
            name="data_registro_inicio",
            field=models.DateField(
                help_text="Data em que o sistema registrou esta informação (transaction_time - início)",
                verbose_name="Data de Registro Início",
            ),
        ),
        migrations.AlterField(
            model_name="versaoclassificacao",
            name="data_registro_fim",
            field=models.DateField(
                help_text="Data em que esta informação deixou de ser considerada verdadeira pelo sistema (transaction_time - fim). Valor sentinela 9999-12-31 indica registro ativo.",
                verbose_name="Data de Registro Fim",
            ),
        ),
        migrations.AlterField(
            model_name="versaoclassificacao",
            name="data_registro_inicio",
            field=models.DateField(
                help_text="Data em que o sistema registrou esta informação (transaction_time - início)",
                verbose_name="Data de Registro Início",
            ),
        ),
    ]
